# See 02-workflow-events/README.md for more information
# about different triggers for GitHub Actions.

name: 02 - Workflow Events

on: 
    # push:
    workflow_dispatch:
    # pull_request:
    # schedule:
    #     - cron: '*/5 * * * *'     # documentation says runs every 5 min but it's really every 15 min.

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show the trigger
              run: echo "I've been triggered by a(n) ${{ github.event_name }} event."
