
name: 03 - Workflow Runners
on: 
    push:

jobs:
    ubuntu-echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show OS
              run: echo "This job is running ${{ GitHub.OS }}"
    windows-echo:
        runs-on: windows-latest
        steps:
            - name: Show OS
              shell: bash
              run: echo "This job is running ${{ GitHub.OS }}"
    mac-echo:
        runs-on: macos-latest
        steps:
            - name: Show OS
              run: echo "This job is running ${{ GitHub.OS }}"
        