name: 07-Working-with-expressions

run-name: 07 - Expressions | DEBUG - ${{ inputs.debug }}

on:
    push:
    workflow_dispatch: 
        inputs:
            debug:
                type: boolean
                default: false

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
          - name: Print start-up data [debug]
          - if: ${{ inputs.debug }} == 'true'
            run: |
              echo "Triggered by: ${{ GitHub.event }}"
              echo "Branch: ${{ GitHub.Branch }}"
              echo "Commit SHA: ${{ GitHub.SHA}}"
              echo "Runner OS: $RunnerOS"
          - name: Print start-up data triggered from main [debug]
          - if: ${{ inputs.debug }} == 'true' && ${{ GitHub.Branch}} == 'main'
            run: |
              echo "Triggered by: ${{ GitHub.event }}"
              echo "Branch: ${{ GitHub.Branch }}"
              echo "Commit SHA: ${{ GitHub.SHA}}"
              echo "Runner OS: $RunnerOS"
          - name: Greetings
              run: echo "Hello World!!"