name: 07-Working-with-expressions

run-name: 07 - Expressions | DEBUG - ${{ inputs.debug }}

on:
    push:
    workflow_dispatch: 
        inputs:
            debug:
                type: boolean
                default: false

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
          - name: 'Print startu-up data [debug]'
            if: ${{ inputs.debug }} == 'true'
            run: |
              echo "Triggered by: ${{ GitHub.event }}"
              echo "Branch: ${{ GitHub.ref_name }}"
              echo "Commit SHA: ${{ GitHub.SHA}}"
              echo "Runner OS: $RUNNER_OS"
          - name: 'Print start-up data triggered from main [debug]'
            if: ${{ inputs.debug }} == 'true' && ${{ GitHub.ref_name}} == 'main'
            run: |
              echo "Triggered by: ${{ GitHub.event }}"
              echo "Branch: ${{ GitHub.ref_name }}"
              echo "Commit SHA: ${{ GitHub.SHA}}"
              echo "Runner OS: $RUNNER_OS"
          - name: Greetings
            run: |
              echo "Hello world!!!"